### ISSUE TITLE
Add region on AddressDTO object so I can display the correct data on address via region

### ISSUE THREAD

**Issue by jc4balos** [Elleined/philippines-location-api#1]

**Comment by jc4balos** [comment]
![image](https://github.com/Elleined/philippines-location-api/assets/66464582/3880cf94-5b06-4be3-82bf-573c90495f9a)
cant display address since it is dependent on region @Elleined

**Comment by Elleined** [comment]
- drop and create database 
- maven clean
- When saving user also include now the region name now check postman endpoint for new user json template
